### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by colorworlds** [Suecra/Pokemon_Maker#4]
Hello, I'm a newcomer to Godot engine. I like the pokemon, too , So I want to learn about this project. 
But after I download the project, I find it seems that there are many problems in the project. Even I haven't found an image in the project.  I found a lot of files called **Thumbs.db**. This seems to be some kind of binary format file that I can't open with a text editor.
 I'm very confused about how to use this project. Can you give me some suggestions. thank you very much.

**Comment by Suecra** [comment]
Hi, if you want to use the scripts, you first have to create a new project in the godot-launcher, than copy the files into your project folder. For testing purposes, i used some of the official graphics, which aren't included in the repository cause i don't own them. In general, the project is still in the very early stages, so i don't recommend using it for a game right now. But i will work a lot on it in the following weeks and also add a readme.txt for better understanding.

**Comment by colorworlds** [comment]
> Hi, if you want to use the scripts, you first have to create a new project in the godot-launcher, than copy the files into your project folder. For testing purposes, i used some of the official graphics, which aren't included in the repository cause i don't own them. In general, the project is still in the very early stages, so i don't recommend using it for a game right now. But i will work a lot on it in the following weeks and also add a readme.txt for better understanding.

Good luck with your work
